import type { Metadata } from "next";
import { Gabarito } from 'next/font/google'
import "./globals.css";

const gabarito = Gabarito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gabarito.className} antialiased h-screen flex-1`}
      >
        {children}
      </body>
    </html>
  );
}
